
<div class="col-md-6 m40" style="text-align:justify;">
     <div class="message-box">

         <h3>Rapport du symposium de Recherche en Informatique – Bobo-Dioulasso Novembre 2018</h3>
         <p> Publié le 26 avril 2019 par AdminEsi </p>
         <p>L’Équipe de Recherche en Informatique pour le Développement Durable (EI2D) du Laboratoire d’Analyse de Mathématique Discrète et Informatique (LAMDI) et la section IEEE Burkina ont organisé  le jeudi 22 novembre 2018
           au Centre de Formation et de Recherche de l’Université Nazi BONI un mini symposium de recherche en informatique. Au cours de ce symposium, six travaux de recherche ont été présentés. Ces présentations ont concerné aussi bien des articles déjà présentés
           (essentiellement à des conférences IEEE) que de nouveaux projets en cours de maturation. </p>

     </div><!-- end messagebox -->
 </div><!-- end col -->
 <div class="col-md-6">
     <div class="post-media wow fadeIn">
         <img src="img/images/img-01.jpg" class="img-responsive img-rounded">
         <a data-rel="prettyPhoto[gal]" class="playbutton"><i class="flaticon-play-button"></i></a>
     </div><!-- end media -->
 </div><!-- end col -->

 <div class="col-md-12 m40" style="text-align:justify;">
     <div class="message-box">

         <h3>Session de formation des secrétaires à l’environnement GNU/LiInux Ubuntu, Libre office et Outils du web</h3>
         <p> Publié le 26 avril 2019 par AdminEsi </p>
         <p>Le Directeur de l’Ecole Supérieure de l’Informatique, le Directeur du Service Informatique  et le  Sécrétaire Général de l’université NAZI Boni ont procédé au lancement officiel de la session de formation des secrétaires à l’environnement GNU/LiInux Ubuntu,
           Libre office et Outils du web à la Bibliothèque Universitaire Centrale.
           L’ESI accompagne fortement cette initiative. Ces séances de formations s’étalerons sur les trois mois à venir. Les formations ont lieu tous les mardi et jeudi de 10h à 13h et concernent Libre office traitement de texte (writer), office tableur, office présentation, gestion électronique de courrier (y compris messagerie électronique), sécurité des outils/services web, e-réputation de nos établissements. </p>

     </div><!-- end messagebox -->
 </div><!-- end col -->
