<div class="col-md-10 m40" style="text-align:justify;">
     <div class="message-box">

         <h2>Les futurs étudiants</h2>
         <h3> Licence en Informatique </h3>
         <p> <u> <strong>Le concours d'entré</strong> </u> </p>
         <p> <u>Critère d’accès :  </u> </p>

        <p>Pour pouvoir prendre part au concours d’entrée il faut remplir les conditions suivantes :</p>
        <p>
            <ul>
               <li>   Etre titulaire d’un bac scientifique de la session précédente ; </li>
                <li>  Avoir déposé un dossier d’inscription à l’ESI  (*) ; </li>
                 <li> Avoir payé les frais de participation au concours qui s’élèvent à 15000FCFA.(*) </li>

             </ul>
       </p>

       <p> Constitution du dossier d’inscription en licence:</p>
       <p>
           <ul>
              <li> Une demande manuscrite timbrée à 200FCFA adressée au  ministre de l’enseignement de l’enseignement secondaire et supérieur ; </li>
               <li>   Une photocopie légalisée de l’attestation du baccalauréat ;</li>
                <li> Une photocopie légalisée des relevés de notes au baccalauréat ;</li>
                <li> Un certificat de nationalité ;</li>
            </ul>
      </p>

      <p> Le nombre de places réservées aux candidats est fixé à cinquante (50).</p>
      <p> Epreuves </p>
      <p>
          <ul>
             <li>   Mathématiques 1 (Coef. 4, durée 4 h) </li>
              <li>    Mathématiques 2 (Coef. 4, durée 4 h)</li>
               <li> Physique (Coef. 4, durée 4 h)</li>
               <li> Français (Coef. 2, durée 4 h)</li>
               <li>   Anglais (Coef. 2, durée 2 h)</li>
           </ul>
      </p>


     </div><!-- end messagebox -->
 </div><!-- end col -->
