<?php

$titre = 'Supprimer un livre';
$url   = $this->url('bibliotheque', ['action' => 'delete', 'id' => $id]);

$this->headTitle($titre);
?>
<h1><?= $this->escapeHtml($titre) ?></h1>

<p>
  Etes vous sûr de vouloir supprimer le livre
    <?= $this->escapeHtml($bibliotheque->titre) ?> parrue
    <?= $this->escapeHtml($bibliotheque->annee) ?>
    ecrit par <?= $this->escapeHtml($bibliotheque->auteur) ?> qui
    <?= $this->escapeHtml($bibliotheque->resume) ?> ?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $bibliotheque->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Oui" />
    <input type="submit" class="btn btn-success" name="del" value="Non" />
</div>
</form>
