<div class="col-md-6 m40" style="text-align:justify;">
     <div class="message-box">

         <h3>Présentation de l'école superieure d'informatique ESI</h3>
         <p> L’ESI a été créée en 1990 à Ouagadougou, il a été déplacée à Bobo-Dioulasso en 1995 à la faveur
            de la création du Centre Universitaire Polytechnique de Bobo-Dioulasso (CUPB) qui est devenu
            en 1997 Université Polytechnique de Bobo-Dioulasso (UPB) rebaptisée Université Nazi BONI
            (UNB) le 8 mai 2017. L’ESI est sur le campus de Nasso et suit partiellement le système Licence
            Master Doctorat (LMD). En effet, l’ancien Cycle des Ingénieurs de Travaux Informatiques (CITI),
            d’une durée de trois ans, est devenu une licence d’informatique. La licence offre deux spécialités :
            Ingénierie des réseaux et systèmes (anciennement « Réseaux et maintenance informatiques, REMI
            ») et Ingénierie des systèmes d’information (anciennement « Analyse et programmation, AP »). A
            la tête de l’ESI il y a un directeur assisté d'un directeur adjoint. Le corps professoral de
            l’établissement est constitué d’enseignants qualifiés nationaux et internationaux. </p>
         <p>L’ESI délivre les diplômes  de :

            <strong>Licence en informatique (BAC+3) </strong>
            <ul>
               <li> Option Système d’Information (SI) </li>
               <li> Option Réseaux et Systèmes (RS) </li>
            </ul>
            <strong>Master en informatique (BAC+5) </strong>
            <ul>
               <li> Option SI parcours Système d’Aide à la Décision (SAD) </li>
               <li> Option RS parcours Conception et Architecture des Réseaux (CAR)  </li>
            </ul>
       </p>

     </div><!-- end messagebox -->
 </div><!-- end col -->
 <div class="col-md-6">
     <div class="post-media wow fadeIn">
         <img src="img/logo.jpg" class="img-responsive img-rounded">
         <a data-rel="prettyPhoto[gal]" class="playbutton"><i class="flaticon-play-button"></i></a>
     </div><!-- end media -->
 </div><!-- end col -->
