<div class="col-md-10 m40" style="text-align:justify;">
     <div class="message-box">

         <h3>Les anciens étudiants</h3>


       <p> Constitution du dossier d’inscription en licence:</p>
       <p> Le concours comprend des épreuves écrites d’admissibilité et un entretien.
         Les candidats déclarés admissibles seront convoqués à un entretien de 15 min devant un jury.
         Il s’agira pour eux de répondre aux questions sur leurs parcours académiques et professionnels, leurs motivations, leurs compétences, leurs projets professionnels. Ils devront être physiquement présents au lieu de l’entretien, munis des documents qu’ils jugeront importants à présenter aux membres du jury.</p>
     </div><!-- end messagebox -->
 </div><!-- end col -->
