<?php
$titre = 'Ajouter un etudiant';
$this->headTitle($titre);
?>
<h1><?= $this->escapeHtml($titre) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the Nom element:
$nom = $form->get('nom');
$nom->setAttribute('class', 'form-control');
$nom->setAttribute('placeholder', 'Nom');

// This provides a default CSS class and placeholder text for the Prenom element:
$prenom = $form->get('prenom');
$prenom->setAttribute('class', 'form-control');
$prenom->setAttribute('placeholder', 'Prenom');

// This provides a default CSS class and placeholder text for the Age element:
$age = $form->get('age');
$age->setAttribute('class', 'form-control');
$age->setAttribute('placeholder', 'Age');

// This provides a default CSS class and placeholder text for the Age element:
$universite = $form->get('universite');
$universite ->setAttribute('class', 'form-control');
$universite ->setAttribute('placeholder', 'Universite');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('etudiant', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($nom) ?>
    <?= $this->formElement($nom) ?>
    <?= $this->formElementErrors()->render($nom, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($prenom) ?>
    <?= $this->formElement($prenom) ?>
    <?= $this->formElementErrors()->render($prenom, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($age) ?>
    <?= $this->formElement($age) ?>
    <?= $this->formElementErrors()->render($age, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($universite) ?>
    <?= $this->formElement($universite) ?>
    <?= $this->formElementErrors()->render($universite, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
