<?php

$titre = 'Supprimer un etudiant';
$url   = $this->url('etudiant', ['action' => 'delete', 'id' => $id]);

$this->headTitle($titre);
?>
<h1><?= $this->escapeHtml($titre) ?></h1>

<p>
  Etes vous sûr de vouloir supprimer l'etudiant
    <?= $this->escapeHtml($etudiant->nom) ?>
    <?= $this->escapeHtml($etudiant->prenom) ?>
    <?= $this->escapeHtml($etudiant->age) ?> ans
    de <?= $this->escapeHtml($etudiant->universite) ?> ?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $etudiant->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Oui" />
    <input type="submit" class="btn btn-success" name="del" value="Non" />
</div>
</form>
