<?php


$titre = 'Modifier un etudiant';
$this->headTitle($titre);
?>
<h1><?= $this->escapeHtml($titre) ?></h1>
<?php
$nom = $form->get('nom');
$nom->setAttribute('class', 'form-control');
$nom->setAttribute('placeholder', 'Nom');

$prenom = $form->get('prenom');
$prenom->setAttribute('class', 'form-control');
$prenom->setAttribute('placeholder', 'Prenom');

$age = $form->get('age');
$age->setAttribute('class', 'form-control');
$age->setAttribute('placeholder', 'Age');

$universite = $form->get('universite');
$universite->setAttribute('class', 'form-control');
$universite->setAttribute('placeholder', 'Universite');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('etudiant', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($nom) ?>
    <?= $this->formElement($nom) ?>
    <?= $this->formElementErrors()->render($nom, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($prenom) ?>
    <?= $this->formElement($prenom) ?>
    <?= $this->formElementErrors()->render($prenom, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($age) ?>
    <?= $this->formElement($age) ?>
    <?= $this->formElementErrors()->render($age, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($universite) ?>
    <?= $this->formElement($universite) ?>
    <?= $this->formElementErrors()->render($universite, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
